import { useParams } from "react-router-dom";
import { useEffect, useState } from "react";

export default function PublicReport(){

const { id } = useParams();

const [report,setReport] = useState(null);

useEffect(()=>{

async function load(){

const res = await fetch(
`https://ai-chat-backend.onrender.com/report/${id}`
);

const data = await res.json();

setReport(data);

}

load();

},[id]);

if(!report){

return <div>Loading report...</div>;

}

return(

<div className="page">

<h1>Export Intelligence Report</h1>

<div className="card">

<p><b>Product:</b> {report.product}</p>
<p><b>Destination:</b> {report.country}</p>
<p><b>HS Code:</b> {report.hs_code}</p>
<p><b>Risk:</b> {report.risk_level}</p>

</div>

<div className="card">

<h3>Required Documents</h3>

<ul>
{report.documents.map((d,i)=>(
<li key={i}>{d}</li>
))}
</ul>

</div>

<div style={{marginTop:40}}>

<b>Generated by Export AI Agent</b>

<br/>

<button className="btn">

Create your own export report

</button>

</div>

</div>

);

}